# Generated by Django 2.2 on 2020-09-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200914_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': {('perm_user', 'разрешение пользователя')}, 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
