# Generated by Django 2.2 on 2020-08-13 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200813_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Описание'),
        ),
    ]
