# Generated by Django 2.2 on 2020-08-15 14:40

from django.db import migrations, models
import webapp.validations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200813_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=3000, validators=[webapp.validations.symbols_20], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=300, validators=[webapp.validations.symbols_3], verbose_name='Краткое описание'),
        ),
    ]
