# Generated by Django 2.2 on 2020-08-22 08:20

from django.db import migrations, models
import webapp.validations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200815_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[webapp.validations.symbols_3], verbose_name='Название')),
                ('description', models.TextField(max_length=3000, validators=[webapp.validations.symbols_20], verbose_name='Описание')),
                ('start_date_at', models.DateField(verbose_name='Дата начала')),
                ('end_date_at', models.DateField(blank=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
