# Generated by Django 2.2 on 2020-09-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
